---
- name: Install keepalived
  yum: 
    name: keepalived
    state: present
  become: yes
  tags: 
    - keepalived

- name: Deploy the healthcheck script
  template: 
    src: healthcheck.sh.j2 
    dest: /etc/keepalived/healthcheck.sh
    mode: 0755
    owner: root
    group: root
  become: yes
  tags: keepalived
  notify: restart keepalived

- name: Deploy the configuration file
  template: 
    src: keepalived.conf.j2 
    dest: /etc/keepalived/keepalived.conf
  become: yes
  tags: 
    - keepalived
  notify: restart keepalived

- name: Ensure keepalived is running
  service: 
    name: keepalived 
    state: started
  become: yes
  tags: 
    - keepalived
